### ISSUE TITLE
🛣️ Roadmap

### ISSUE THREAD

**Issue by tjarbo** [tjarbo/pipeline-notifier-browser-ext#1]
# 🛣️ Roadmap

The purpose of this issue is to easily communicate and coordinate the planned features of the browser extensions. It can be also used to provide comments and ideas for the roadmap.

## Supported Pipeline Engines:

- [ ] GitHub Actions
- [ ] Jenkins
- [ ] TravisCI
- [ ] More to be determined.

## Other Features

- [ ] Devcontainer setup for easy collaboration
- [ ] Publish extension to Firefox Store
- [ ] Publish extension to Chrome Store
